// <auto-generated />
namespace TrashPickup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcityandstate1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcityandstate));
        
        string IMigrationMetadata.Id
        {
            get { return "201707052149264_added city and state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
